name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/closestpair-be:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/closestpair-be:latest

  deploy:
    needs: build
    runs-on: cadevue-station

    steps:
      - name: Pull latest Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/closestpair-be:latest

      - name: Stop and remove old container (if exists)
        run: |
          docker stop closestpair-be || true
          docker rm closestpair-be || true

      - name: Run new container
        run: |
          docker run -d --restart unless-stopped -p 8080:8080 --name closestpair-be ${{ secrets.DOCKER_USERNAME }}/closestpair-be:latest

      - name: Clean up old images
        run: |
          docker image prune -f
